[package]
name = "babel"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["babel-macros"]

[dependencies]
anyhow = "1.0.100"
dashmap = "6.1.0"
log = "0.4.29"
env_logger = "0.11.9"

[dev-dependencies]
babel-macros = { path = "babel-macros" }
ctrlc = { version = "3.5.2" }
rand = "0.10.0"
uuid = { version = "1.20.0", features = ["v4"] }

[[example]]
name = "chat_app"
path = "examples/chat_app/main.rs"

